-- Schema for Offline POS

-- pos_profiles: Stores POS profile configurations.
CREATE TABLE pos_profiles (
    name TEXT PRIMARY KEY,
    company TEXT,
    warehouse TEXT,
    currency TEXT,
    selling_price_list TEXT,
    income_account TEXT,
    expense_account TEXT,
    cost_center TEXT
);

-- items: Stores item master data.
CREATE TABLE items (
    item_code TEXT PRIMARY KEY,
    item_name TEXT,
    item_group TEXT,
    brand TEXT,
    stock_uom TEXT,
    is_stock_item INTEGER, -- 0 for No, 1 for Yes
    disabled INTEGER,      -- 0 for No, 1 for Yes
    barcodes_searchable TEXT, -- JSON string array for barcodes
    uoms_searchable TEXT      -- JSON string array for UOMs
);
CREATE INDEX idx_items_item_name ON items (item_name);
CREATE INDEX idx_items_item_group ON items (item_group);
CREATE INDEX idx_items_brand ON items (brand);

-- item_prices: Stores item prices for different price lists.
CREATE TABLE item_prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_code TEXT,
    price_list TEXT,
    price_list_rate REAL,
    currency TEXT,
    uom TEXT,
    UNIQUE (item_code, price_list)
);
CREATE INDEX idx_item_prices_item_code ON item_prices (item_code);
CREATE INDEX idx_item_prices_price_list ON item_prices (price_list);

-- customers: Stores customer master data.
CREATE TABLE customers (
    name TEXT PRIMARY KEY,
    customer_name TEXT,
    customer_group TEXT,
    default_price_list TEXT,
    disabled INTEGER -- 0 for No, 1 for Yes
);
CREATE INDEX idx_customers_customer_name ON customers (customer_name);
CREATE INDEX idx_customers_customer_group ON customers (customer_group);

-- warehouses: Stores warehouse master data.
CREATE TABLE warehouses (
    name TEXT PRIMARY KEY,
    warehouse_name TEXT,
    company TEXT
);

-- stock_levels: Stores actual stock quantities for items in warehouses.
CREATE TABLE stock_levels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_code TEXT,
    warehouse TEXT,
    actual_qty REAL,
    UNIQUE (item_code, warehouse)
);
CREATE INDEX idx_stock_levels_item_code ON stock_levels (item_code);
CREATE INDEX idx_stock_levels_warehouse ON stock_levels (warehouse);

-- payment_modes: Stores different modes of payment.
CREATE TABLE payment_modes (
    name TEXT PRIMARY KEY,
    mode_of_payment TEXT,
    type TEXT -- E.g., 'Cash', 'Card', 'Bank'
);
CREATE INDEX idx_payment_modes_type ON payment_modes (type);

-- tax_templates: Stores tax template configurations.
CREATE TABLE tax_templates (
    name TEXT PRIMARY KEY,
    title TEXT,
    company TEXT
);

-- company_settings: Stores company-specific settings.
-- Assuming 'name' refers to a unique setting key or company identifier for the setting.
CREATE TABLE company_settings (
    name TEXT PRIMARY KEY, -- e.g., 'global_settings' or company name if multi-company setup in one DB
    default_currency TEXT
);

-- offline_transactions: Stores transactions made while offline.
CREATE TABLE offline_transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    offline_id TEXT UNIQUE, -- Local reference ID generated by the client
    customer TEXT,
    transaction_date TEXT, -- ISO8601 format
    sync_status TEXT,      -- e.g., 'pending', 'synced', 'failed'
    pos_profile TEXT,
    company TEXT,
    error_message TEXT,    -- To store any sync error messages
    transaction_data TEXT  -- JSON string holding the full transaction details
);
CREATE INDEX idx_offline_transactions_sync_status ON offline_transactions (sync_status);
CREATE INDEX idx_offline_transactions_customer ON offline_transactions (customer);
CREATE INDEX idx_offline_transactions_transaction_date ON offline_transactions (transaction_date);
CREATE INDEX idx_offline_transactions_pos_profile ON offline_transactions (pos_profile);


-- held_carts: Stores carts that are temporarily saved.
CREATE TABLE held_carts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    held_at TEXT,          -- ISO8601 timestamp when the cart was held
    name TEXT,             -- Optional name for the cart
    cart_data TEXT         -- JSON string containing all cart details (items, customer, totals, etc.)
);
CREATE INDEX idx_held_carts_held_at ON held_carts (held_at);
CREATE INDEX idx_held_carts_name ON held_carts (name);
