const schemaSQL = `
-- Schema for Offline POS

-- pos_profiles: Stores POS profile configurations.
CREATE TABLE pos_profiles (
    name TEXT PRIMARY KEY,
    company TEXT,
    warehouse TEXT,
    currency TEXT,
    selling_price_list TEXT,
    income_account TEXT,
    expense_account TEXT,
    cost_center TEXT
);

-- items: Stores item master data.
CREATE TABLE items (
    item_code TEXT PRIMARY KEY,
    item_name TEXT,
    item_group TEXT,
    brand TEXT,
    stock_uom TEXT,
    is_stock_item INTEGER, -- 0 for No, 1 for Yes
    disabled INTEGER,      -- 0 for No, 1 for Yes
    barcodes_searchable TEXT, -- JSON string array for barcodes
    uoms_searchable TEXT      -- JSON string array for UOMs
);
CREATE INDEX idx_items_item_name ON items (item_name);
CREATE INDEX idx_items_item_group ON items (item_group);
CREATE INDEX idx_items_brand ON items (brand);

-- item_prices: Stores item prices for different price lists.
CREATE TABLE item_prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_code TEXT,
    price_list TEXT,
    price_list_rate REAL,
    currency TEXT,
    uom TEXT,
    UNIQUE (item_code, price_list)
);
CREATE INDEX idx_item_prices_item_code ON item_prices (item_code);
CREATE INDEX idx_item_prices_price_list ON item_prices (price_list);

-- customers: Stores customer master data.
CREATE TABLE customers (
    name TEXT PRIMARY KEY,
    customer_name TEXT,
    customer_group TEXT,
    default_price_list TEXT,
    disabled INTEGER -- 0 for No, 1 for Yes
);
CREATE INDEX idx_customers_customer_name ON customers (customer_name);
CREATE INDEX idx_customers_customer_group ON customers (customer_group);

-- warehouses: Stores warehouse master data.
CREATE TABLE warehouses (
    name TEXT PRIMARY KEY,
    warehouse_name TEXT,
    company TEXT
);

-- stock_levels: Stores actual stock quantities for items in warehouses.
CREATE TABLE stock_levels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_code TEXT,
    warehouse TEXT,
    actual_qty REAL,
    UNIQUE (item_code, warehouse)
);
CREATE INDEX idx_stock_levels_item_code ON stock_levels (item_code);
CREATE INDEX idx_stock_levels_warehouse ON stock_levels (warehouse);

-- payment_modes: Stores different modes of payment.
CREATE TABLE payment_modes (
    name TEXT PRIMARY KEY,
    mode_of_payment TEXT,
    type TEXT -- E.g., 'Cash', 'Card', 'Bank'
);
CREATE INDEX idx_payment_modes_type ON payment_modes (type);

-- tax_templates: Stores tax template configurations.
CREATE TABLE tax_templates (
    name TEXT PRIMARY KEY,
    title TEXT,
    company TEXT
);

-- company_settings: Stores company-specific settings.
-- Assuming 'name' refers to a unique setting key or company identifier for the setting.
CREATE TABLE company_settings (
    name TEXT PRIMARY KEY, -- e.g., 'global_settings' or company name if multi-company setup in one DB
    default_currency TEXT
);

-- offline_transactions: Stores transactions made while offline.
CREATE TABLE offline_transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    offline_id TEXT UNIQUE, -- Local reference ID generated by the client
    customer TEXT,
    transaction_date TEXT, -- ISO8601 format
    sync_status TEXT,      -- e.g., 'pending', 'synced', 'failed'
    pos_profile TEXT,
    company TEXT,
    error_message TEXT,    -- To store any sync error messages
    transaction_data TEXT  -- JSON string holding the full transaction details
);
CREATE INDEX idx_offline_transactions_sync_status ON offline_transactions (sync_status);
CREATE INDEX idx_offline_transactions_customer ON offline_transactions (customer);
CREATE INDEX idx_offline_transactions_transaction_date ON offline_transactions (transaction_date);
CREATE INDEX idx_offline_transactions_pos_profile ON offline_transactions (pos_profile);


-- held_carts: Stores carts that are temporarily saved.
CREATE TABLE held_carts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    held_at TEXT,          -- ISO8601 timestamp when the cart was held
    name TEXT,             -- Optional name for the cart
    cart_data TEXT         -- JSON string containing all cart details (items, customer, totals, etc.)
);
CREATE INDEX idx_held_carts_held_at ON held_carts (held_at);
CREATE INDEX idx_held_carts_name ON held_carts (name);
`;

let dbInstance = null;

// Helper to parse JSON strings from DB
function parseJSON(jsonString, defaultValue = null) {
    if (jsonString === null || typeof jsonString === 'undefined') return defaultValue;
    try {
        return JSON.parse(jsonString);
    } catch (e) {
        console.error("Failed to parse JSON:", e, "String was:", jsonString);
        return defaultValue;
    }
}

// Helper to stringify objects for DB
function stringifyJSON(value, defaultValue = null) {
    if (typeof value === 'string') return value; // Already a string
    try {
        return JSON.stringify(value);
    } catch (e) {
        console.error("Failed to stringify JSON:", e, "Value was:", value);
        return defaultValue;
    }
}


async function getDbInstance() {
    if (dbInstance) {
        return dbInstance;
    }
    try {
        const db = await window.__TAURI__.sql.load("sqlite:offline_pos.db");
        // Check if tables exist by checking one key table
        const result = await db.select("SELECT name FROM sqlite_master WHERE type='table' AND name='items';");

        if (result.length === 0) {
            console.log("Database tables not found, initializing schema...");
            // Split schema into individual statements (some SQL drivers/plugins prefer one statement at a time)
            const ddlCommands = schemaSQL.split(';').map(cmd => cmd.trim()).filter(cmd => cmd.length > 0);
            for (const command of ddlCommands) {
                await db.execute(command);
            }
            console.log("Database schema initialized.");
        }
        dbInstance = db;
        return dbInstance;
    } catch (error) {
        console.error("Failed to initialize database:", error);
        throw error; // Re-throw to indicate failure
    }
}

export async function replaceAllData(tableName, dataArray) {
    const db = await getDbInstance();
    try {
        await db.execute(`DELETE FROM ${tableName}`); // Clear the table
        if (!dataArray || dataArray.length === 0) {
            console.log(`No data provided for ${tableName}, table cleared.`);
            return;
        }

        // Prepare column names and placeholders
        // Assumes all objects in dataArray have the same keys
        const firstItem = dataArray[0];
        const columns = Object.keys(firstItem);
        const placeholders = columns.map(() => '?').join(','); // ?,?,?

        const insertQuery = `INSERT INTO ${tableName} (${columns.join(',')}) VALUES (${placeholders})`;

        for (const item of dataArray) {
            let values = columns.map(col => {
                // Handle JSON stringification for specific fields based on common patterns
                if (['barcodes_searchable', 'uoms_searchable', 'transaction_data', 'cart_data'].includes(col)) {
                    return stringifyJSON(item[col]);
                }
                // Handle boolean to integer conversion
                if (typeof item[col] === 'boolean') {
                    return item[col] ? 1 : 0;
                }
                return item[col];
            });
            await db.execute(insertQuery, values);
        }
        console.log(`Successfully populated ${tableName} with ${dataArray.length} records.`);
    } catch (error) {
        console.error(`Error in replaceAllData for table ${tableName}:`, error);
        // Consider re-throwing or specific error handling
        throw error;
    }
}


// --- POS Profile ---
export async function savePOSProfile(profile) {
    const db = await getDbInstance();
    const query = `
        INSERT OR REPLACE INTO pos_profiles 
        (name, company, warehouse, currency, selling_price_list, income_account, expense_account, cost_center) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `;
    await db.execute(query, [
        profile.name, profile.company, profile.warehouse, profile.currency,
        profile.selling_price_list, profile.income_account, profile.expense_account, profile.cost_center
    ]);
}

export async function getPOSProfile(name) {
    const db = await getDbInstance();
    const result = await db.select("SELECT * FROM pos_profiles WHERE name = ?", [name]);
    return result.length > 0 ? result[0] : null;
}

// --- Items ---
export async function searchItems(searchTerm) {
    const db = await getDbInstance();
    if (!searchTerm) {
        return await db.select("SELECT * FROM items LIMIT 100");
    }
    const term = `%${searchTerm}%`;
    // Searching barcodes_searchable as a JSON string. This is basic.
    // For more advanced JSON search, SQLite's JSON1 extension would be needed, but LIKE can work for simple cases.
    // Assuming barcodes are stored like '["bc1","bc2"]'
    const barcodeSearchTerm = `%"${searchTerm}"%`; 
    const query = `
        SELECT * FROM items 
        WHERE LOWER(item_name) LIKE LOWER(?) 
           OR LOWER(item_code) LIKE LOWER(?)
           OR barcodes_searchable LIKE ? 
        LIMIT 50
    `;
    return await db.select(query, [term, term, barcodeSearchTerm]);
}

export async function getItemByCode(itemCode) {
    const db = await getDbInstance();
    const result = await db.select("SELECT * FROM items WHERE item_code = ?", [itemCode]);
    if (result.length > 0) {
        const item = result[0];
        item.barcodes_searchable = parseJSON(item.barcodes_searchable, []);
        item.uoms_searchable = parseJSON(item.uoms_searchable, []);
        return item;
    }
    return null;
}

export async function getItemByBarcode(barcode) {
    const db = await getDbInstance();
    // This assumes barcode is a string value within the JSON array stored in barcodes_searchable
    const searchTerm = `%"${barcode}"%`; // e.g. finds "12345" in '["abc","12345","def"]'
    const query = "SELECT * FROM items WHERE barcodes_searchable LIKE ?";
    const results = await db.select(query, [searchTerm]);
    if (results.length > 0) {
        const item = results[0];
        item.barcodes_searchable = parseJSON(item.barcodes_searchable, []);
        item.uoms_searchable = parseJSON(item.uoms_searchable, []);
        return item; // Return the first match
    }
    return null;
}


// --- Item Prices ---
export async function getItemPrice(itemCode, priceList) {
    const db = await getDbInstance();
    const result = await db.select(
        "SELECT * FROM item_prices WHERE item_code = ? AND price_list = ?",
        [itemCode, priceList]
    );
    return result.length > 0 ? result[0] : null;
}

export async function getAllItemPrices() {
    const db = await getDbInstance();
    return await db.select("SELECT * FROM item_prices");
}

// --- Customers ---
export async function searchCustomers(searchTerm) {
    const db = await getDbInstance();
    if (!searchTerm) {
        return await db.select("SELECT * FROM customers LIMIT 100");
    }
    const term = `%${searchTerm}%`;
    const query = `
        SELECT * FROM customers 
        WHERE LOWER(customer_name) LIKE LOWER(?) 
           OR LOWER(name) LIKE LOWER(?) 
        LIMIT 50
    `;
    return await db.select(query, [term, term]);
}

export async function getCustomerByName(name) {
    const db = await getDbInstance();
    const result = await db.select("SELECT * FROM customers WHERE name = ?", [name]);
    return result.length > 0 ? result[0] : null;
}

// --- Stock Levels ---
export async function getStockLevel(itemCode, warehouse) {
    const db = await getDbInstance();
    const result = await db.select(
        "SELECT * FROM stock_levels WHERE item_code = ? AND warehouse = ?",
        [itemCode, warehouse]
    );
    return result.length > 0 ? result[0] : null;
}

export async function getAllStockLevels() {
    const db = await getDbInstance();
    return await db.select("SELECT * FROM stock_levels");
}

// --- Payment Modes ---
export async function getAllPaymentModes() {
    const db = await getDbInstance();
    return await db.select("SELECT * FROM payment_modes");
}

// --- Offline Transactions ---
export async function saveOfflineTransaction(transaction) {
    const db = await getDbInstance();
    const offlineId = transaction.offline_id || `offline-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    const transactionDate = transaction.transaction_date || new Date().toISOString();
    const syncStatus = transaction.sync_status || 'pending';

    // Extract known fields for specific columns, the rest goes into transaction_data
    const {
        customer, pos_profile, company, // Known top-level fields from schema
        // Potentially other fields if the transaction object is flat
        ...details 
    } = transaction;


    const query = `
        INSERT INTO offline_transactions 
        (offline_id, customer, transaction_date, sync_status, pos_profile, company, transaction_data) 
        VALUES (?, ?, ?, ?, ?, ?, ?)
    `;
    // Note: The 'id' (auto-increment) is not part of insert values.
    // 'details' will capture items, payments, totals, etc.
    const result = await db.execute(query, [
        offlineId, transaction.customer, transactionDate, syncStatus,
        transaction.pos_profile, transaction.company, stringifyJSON(details)
    ]);
    return result.lastInsertId; // Return the auto-incremented ID
}

export async function getPendingTransactions() {
    const db = await getDbInstance();
    const results = await db.select("SELECT * FROM offline_transactions WHERE sync_status = 'pending'");
    return results.map(tx => {
        tx.transaction_data = parseJSON(tx.transaction_data, {});
        return tx;
    });
}

export async function updateTransactionStatus(id, syncStatus, errorMessage = null) {
    const db = await getDbInstance();
    const query = `
        UPDATE offline_transactions 
        SET sync_status = ?, error_message = ? 
        WHERE id = ?
    `;
    await db.execute(query, [syncStatus, errorMessage, id]);
}

// --- Held Carts ---
export async function saveHeldCart(cartData, name = null) {
    const db = await getDbInstance();
    const heldAt = new Date().toISOString();
    const cartName = name || `Cart held at ${new Date(heldAt).toLocaleTimeString()}`;
    
    const query = `
        INSERT INTO held_carts (held_at, name, cart_data) 
        VALUES (?, ?, ?)
    `;
    const result = await db.execute(query, [heldAt, cartName, stringifyJSON(cartData)]);
    return result.lastInsertId;
}

export async function getAllHeldCarts() {
    const db = await getDbInstance();
    const results = await db.select("SELECT * FROM held_carts ORDER BY held_at DESC");
    return results.map(cart => {
        cart.cart_data = parseJSON(cart.cart_data, {});
        return cart;
    });
}

export async function getHeldCart(id) {
    const db = await getDbInstance();
    const result = await db.select("SELECT * FROM held_carts WHERE id = ?", [id]);
    if (result.length > 0) {
        const cart = result[0];
        cart.cart_data = parseJSON(cart.cart_data, {});
        return cart;
    }
    return null;
}

export async function deleteHeldCart(id) {
    const db = await getDbInstance();
    await db.execute("DELETE FROM held_carts WHERE id = ?", [id]);
}


// --- Company Settings ---
// Assuming there's only one row of settings, identified by a known name/key or just the first row.
// For this example, let's assume 'name' is a primary key like 'default_settings'.
// If only one row ever, a simpler approach might be to use ROWID=1 if table is created without primary key.
export async function getCompanySettings(settingsName = "default_settings") {
    const db = await getDbInstance();
    // Adjust if your company_settings table has a different key or logic
    const result = await db.select("SELECT * FROM company_settings WHERE name = ?", [settingsName]);
    return result.length > 0 ? result[0] : null; 
}

export async function saveCompanySettings(settings) {
    const db = await getDbInstance();
    // 'name' would be the primary key, e.g., "default_settings"
    // 'default_currency' is another column from schema
    const query = `
        INSERT OR REPLACE INTO company_settings (name, default_currency) 
        VALUES (?, ?) 
    `;
    // Ensure 'settings.name' exists and matches the key you want to use.
    // If settings object doesn't have 'name', you might hardcode it or adjust.
    const name = settings.name || "default_settings"; 
    await db.execute(query, [name, settings.default_currency]);
}

// --- Warehouses ---
export async function getAllWarehouses() {
    const db = await getDbInstance();
    return await db.select("SELECT * FROM warehouses");
}

// --- Tax Templates ---
export async function getAllTaxTemplates() {
    const db = await getDbInstance();
    return await db.select("SELECT * FROM tax_templates");
}

console.log("SQLite DB helper module loaded (src/sqlite_db.js).");
